### ISSUE TITLE
Zimbra 8.8.6 new install of zimlet

### ISSUE THREAD

**Issue by sasha2002** [Zimbra-Community/account-history#13]
propmigr.jar                                    100%[====================================================================================================>]   1.38K  --.-KB/s    in 0s

2018-02-06 11:34:55 (191 MB/s) - 'propmigr.jar' saved [1414/1414]

java.io.FileNotFoundException: /tmp/accountHistory.o0gQWkxa/upgrade/config.properties (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at tk.barrydegraaff.propMigr.main(propMigr.java:21)
--------------------------------------------------------------------------------------------------------------
Zimbra Account History installed successful.

**Comment by sasha2002** [comment]
An another error ::
Error
columnNumber: 43
fileName: "https://HOST/service/zimlet/_dev/tk_barrydegraaff_account_history/longtable.js?v=171130043602&language=en&country=US&debug=1"
lineNumber: 29
message: "longtable: Missing table <tbody>."

**Comment by ghost** [comment]
The first error is normal, it is a check to see if you already had an existing install of account history, and if so your preferences are stored in the new install.

The other error is usually a cache error, try removing your browser cache, on the server run 
su zimbra -c "zmprov fc all"

Then log on to your zimbra using the clean browser, wait 2 minutes and see if it works.
