### ISSUE TITLE
RFE: Success/Failed indicator in list/table

### ISSUE THREAD

**Issue by jbnance** [Zimbra-Community/account-history#16]
Hello,

I just installed this Zimlet on 8.8.8 from master.  Failed logins show up in the history without any indicator that it was an unsuccessful login (outside of the details displayed when the record is selected).

I'd like to request an additional column that indicates whether the login was successful or failed.  It would be nice if the reason text - "invalid password" or "account lockout" for example - was the text displayed in the column.

**Comment by ghost** [comment]
Perhaps a good idea, but the Zimlet was designed to track usages of the account.

So in case someone knows your passwords or has another way of accessing your account,
you can track it with this zimlet.

The failed password logins, there should be other means in Zimbra to fight those.

**Comment by jbnance** [comment]
If that is the intention I would say there is a bug because failed logins are also showing up in the list.

**Comment by jbnance** [comment]
Just checking in to see if we're understanding each other.  If the purpose of the Zimlet is to track when the account was accessed and where I think it is a bug that failed logins are showing up in the list.  If you agree would you like me to open a separate issue?

**Comment by ghost** [comment]
I think leaving it as is, is best, as there is no good way to filter out everything.

Besides, I used the failed login indicator to track slow-paced brute force login attacks.

**Comment by jbnance** [comment]
Then why reject the request to have a column or some other indicator in the table of events that calls out logins as failed?  IMO it is confusing - and alarming - to mix successful and failed logins in the display.  To the casual observer it can look like they had successful logins from a different country - only the fine print reveals whether a login was successful or not.

**Comment by ghost** [comment]
Added an exclamation icon in case of failed login attempt is in the list, also when the user points the icon with the mouse, a tooltip is shown saying it is a failed auth attempt.

![icon](https://user-images.githubusercontent.com/4353213/44960066-d563a580-aef8-11e8-842c-282120636a70.png)
