### ISSUE TITLE
Reg. Java not found error when installalling Account Hstory Zimlet

### ISSUE THREAD

**Issue by lijulalu** [Zimbra-Community/account-history#19]
Dear Sir,

I am using the following version of Zimbra
Release 8.8.11.GA.3737.UBUNTU16.64 UBUNTU16_64 FOSS edition, Patch 8.8.11_P2.
When I tried to install the account history (account-history-installer.sh)  zimlet in my zimbra 8.8 version its returning me an error

Java is not found in /opt/zimbra

But in 8.7 version (testing server) it installed fine.Why is it so

When i check ed internet I gound that java folder location id different in version 8.8 ,Is it so?

Please help me to find a solution.

NB:- I had tried both admin(root) and zimbra logins)

Regards,
Liju
![java issue](https://user-images.githubusercontent.com/47552835/52617454-b9a7f680-2ebd-11e9-8abe-30536964f2a6.jpg)

**Comment by ghost** [comment]
Can you check the output of the following command:

      [root@mail ~]# ls -hal /opt/zimbra/common/bin/java
      lrwxrwxrwx. 1 root root 24 Jun  8  2018 /opt/zimbra/common/bin/java -> ../lib/jvm/java/bin/java

Our installer looks for the Zimbra distributed Java, and cannot find it on your server.

**Comment by lijulalu** [comment]
Daer Barry,

I did it and its returning the following output.SS attached
![java issue_2](https://user-images.githubusercontent.com/47552835/52631756-752e5200-2ee1-11e9-98bf-958d2ff6053f.jpg)


ls: cannot access '/opt/zimbra/common/bin/javals': No such file or directory
lrwxrwxrwx 1 root root 24 May 28  2018 /opt/zimbra/common/bin/java -> ../lib/jvm/java/bin/java

Regards,
Liju

**Comment by ghost** [comment]
can you re-run the installer with

bash -x /tmp/account-history-installer.sh

Then send me the full output.

**Comment by ghost** [comment]
Tested this yesterday on a 8.8.11 and it works

**Comment by lijulalu** [comment]
> 
> 
> Can you check the output of the following command:
> 
> ```
>   [root@mail ~]# ls -hal /opt/zimbra/common/bin/java
>   lrwxrwxrwx. 1 root root 24 Jun  8  2018 /opt/zimbra/common/bin/java -> ../lib/jvm/java/bin/java
> ```
> 
> Our installer looks for the Zimbra distributed Java, and cannot find it on your server.

Daer Barry,

I did it and its returning the following output.SS attached

Regards,
Liju
![java issue_3](https://user-images.githubusercontent.com/47552835/52710870-492ed180-2fb2-11e9-9e01-02e05ad058ad.jpg)

**Comment by ghost** [comment]
please show output of commands:

      if [[ -e "/opt/zimbra/common/bin/java" ]]; then     echo "true"; else     echo "Java is not found in /opt/zimbra";     exit 1; fi

       if [[ -x "/opt/zimbra/common/bin/java" ]]; then     echo "true"; else     echo "Java is not found in /opt/zimbra";     exit 1; fi

**Comment by lijulalu** [comment]
> 
> 
> please show output of commands:
> 
> ```
>   if [[ -e "/opt/zimbra/common/bin/java" ]]; then     echo "true"; else     echo "Java is not found in /opt/zimbra";     exit 1; fi
> 
>    if [[ -x "/opt/zimbra/common/bin/java" ]]; then     echo "true"; else     echo "Java is not found in /opt/zimbra";     exit 1; fi     
> ```

Now its installing using your command

bash -x /tmp/account-history-installer.sh

Is there any command to uninstall just in case.

Regards,
Liju

**Comment by ghost** [comment]
https://github.com/Zimbra-Community/account-history#un-installing
