### ISSUE TITLE
Multi-servers setup

### ISSUE THREAD

**Issue by KlugFR** [Zimbra-Community/account-history#2]
Hi.

Not really an issue, more a question: does it work with a multi-servers setup (several mailstores)?

**Comment by ghost** [comment]
Hello KlugFR,

Yeah it should work, as long as you make the log from all servers
accessible to the mailbox server.

I was thinking maybe you could use automounter or something like that
and then configure the config.properties to point to all log files.

There may be other options as well.

Regards, Barry

**Comment by sodafire1413** [comment]
Hi,
It isn't working for me. No data recieved from server. 

![capture](https://user-images.githubusercontent.com/35522159/48461187-03246f00-e805-11e8-85c2-6afe269bf148.JPG)



cat config.properties
#Updated by installer via propmigr.
#Wed Nov 14 11:22:25 ICT 2018
audit_logs=/var/log/mail.log;/opt/zimbra/log/audit.log;/opt/zimbra/log/sync.log

cat /opt/zimbra/log/audit.log | grep zsync | grep pongsagorn
2018-11-14 06:38:17,500 INFO  [qtp1798286609-2054772:http://xxxxx/Microsoft-Server-ActiveSync?User=pongsagorn.s&DeviceId=RT50AJNE452139QRP7JP3DJPOO&DeviceType=iPhone&Cmd=Ping] [ip=182.232.xx.xx;] security - cmd=Auth; account=pongsagorn.s@xx.com; protocol=zsync;
