### ISSUE TITLE
The map does not appear zimbra Network 8.8.8

### ISSUE THREAD

**Issue by mrcea** [Zimbra-Community/account-history#20]
hi barry

Thanks for sharing your projects.

I am testing the zimlet, it works very well when showing the ip addresses, but it shows an error message and does not load the map.

**zimbra version**
Release 8.8.8_GA_2009.RHEL7_64_20180322150747 RHEL7_64 NETWORK edition

**redhat version**
NAME = "Red Hat Enterprise Linux Server"
VERSION = "7.5 (Maipo)"
ID = "rhel"
ID_LIKE = "fedora"
VARIANT = "Server"
VARIANT_ID = "server"
VERSION_ID = "7.5"
PRETTY_NAME = "Red Hat Enterprise Linux"

**In mailbox.log i see this error:**

;port=40938;ua=ZimbraWebClient - GC72 (Win)/8.8.8_GA_2009;soapId=2b13956;] SoapEngine - handler exception
java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/InjectableValues
        at com.maxmind.geoip2.DatabaseReader$Builder.build(DatabaseReader.java:160)
        at tk.barrydegraaff.accounthistory.geoIpLookup.doIPGeoLookup(geoIpLookup.java:40)
        at tk.barrydegraaff.accounthistory.accountHistory.handle(accountHistory.java:53)
        at com.zimbra.soap.SoapEngine.dispatchRequest(SoapEngine.java:623)
        at com.zimbra.soap.SoapEngine.dispatch(SoapEngine.java:476)
        at com.zimbra.soap.SoapEngine.dispatch(SoapEngine.java:274)
        at com.zimbra.soap.SoapServlet.doWork(SoapServlet.java:303)
        at com.zimbra.soap.SoapServlet.doPost(SoapServlet.java:213)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at com.zimbra.cs.servlet.ZimbraServlet.service(ZimbraServlet.java:206)

**Message error:**
![2019-03-11_14h21_26](https://user-images.githubusercontent.com/48455362/54155083-01606600-4409-11e9-82cd-7c63db5fc455.png)

**Comment by ghost** [comment]
It seems like a missing Java dependancy, more specifically jackson/databind is not there.

I have to do some digging to see when I added it, and if that was before or after the 8.8.8 release... gimme a sec.

**Comment by ghost** [comment]
This is a dependancy that is called from at com.maxmind.geoip2.DatabaseReader

That was added at the beginning of this year, as Maxmind then pulled there old/legacy geo-ip databases offline.

In other words, this was only tested on Zimbra release 8.8.11 and above.

**Comment by ghost** [comment]
I also see that jackson-databind is in 
/opt/zimbra/lib/jars/jackson-databind-2.9.2.jar

Can you check if it is available on your server?

I think Zimbra added this after 8.8.8 somewhere, if it is not there you can drop one in /opt/zimbra/lib/ext/accountHistory/

Here is a version that I use a lot: https://github.com/Zimbra-Community/owncloud-zimlet/raw/soapServiceBarry/extension/lib/jackson-databind-2.9.4.jar 

Please let me know if it works, I do not think I will be adding this jar to the installer, as it is a part of recent Zimbra releases now.

**Comment by mrcea** [comment]
Hello Barry,

thanks for your reply, I have decided to upgrade to version 8.8.11 my zimbra server, and the zimlet already works very well.

Thank you
