### ISSUE TITLE
Mapa não aparece mesmo com o jackson/ Zimbra 8.8.8_GA_2009 (build 20180322150747)

### ISSUE THREAD

**Issue by leonardochristo1** [Zimbra-Community/account-history#21]
Ao executar aparece o seguinte erro
![erro](https://user-images.githubusercontent.com/32466476/62156995-85e15180-b2e2-11e9-9fd1-ee9c28ed350a.png)

**Comment by ghost** [comment]
you are using an old version of Zimbra. Upgrade to 8.8.15 and try again. 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by leonardochristo1** [comment]
thanks!!

**Comment by ghost** [comment]
The solution to ru on Zimbra 8.7: 

Run the Account History installer, 
then 

cd /opt/zimbra/jetty/common/lib 
wget https://github.com/Zimbra-Community/owncloud-zimlet/raw/soapServiceBarry/extension/lib/jackson-annotations-2.9.4.jar 
wget https://github.com/Zimbra-Community/owncloud-zimlet/raw/soapServiceBarry/extension/lib/jackson-core-2.9.4.jar 
wget https://github.com/Zimbra-Community/owncloud-zimlet/raw/soapServiceBarry/extension/lib/jackson-databind-2.9.4.jar 

Then restart mailbox. 

Do not forget to remove these jars if you upgrade to Zimbra 8.8.15. 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0
