### ISSUE TITLE
Trying to install your zimlet on CENTOS 6 running Zimbra 8.8.15 and I get the following error running the installer. 

### ISSUE THREAD

**Issue by tonyawbrey** [Zimbra-Community/account-history#22]
Installing/updating GeoIP2
--2020-01-14 09:13:24-- https://geolite.maxmind.com/download/geoip/database/GeoLite2-city.tar.gz
Resolving geoLite.maxmind.com... Failed: Name or service not known. 

wget: unable to resolve host address "geolite.maxmind.com"

I tried the url in a browser and can't get to it either.

**Comment by ghost** [comment]
A GDPR change 
[ https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/ | https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/ ] 

We'll have to see how to implement that. 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by axixu** [comment]
hi,

alternatively, you can change to mirror file at https://github.com/DocSpring/geolite2-city-mirror/blob/master/GeoLite2-City.tar.gz

**Comment by ghost** [comment]
fixed the installer and update script

**Comment by tonyawbrey** [comment]
Excellent, thanks Barry I'll give it a try when I have some time! 


Tony Awbrey 
Agilon Software, LLC. 

Phone: 319-739-0766 
8710 Earhart LN SW Suite 8 
Cedar Rapids IA, 52404
