### ISSUE TITLE
Need to edit the Wget part of Fetching from maxmind

### ISSUE THREAD

**Issue by ramalmaty** [Zimbra-Community/account-history#23]
in account-history-installer.sh, Line 132

wget "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=ShaZphSuBJYC5vgf&suffix=tar.gz" -O GeoLite2-City.tar.gz

As per New guidelines of Maxmind:
 If you are using wget or curl from a shell script, please be sure to quote the URL.

Or else it fails, Please edit this.

Thank you for this wonderful Zimlet.

**Comment by ghost** [comment]
it has been done!
