### ISSUE TITLE
Remove sync.log from config.properties

### ISSUE THREAD

**Issue by naisiew** [Zimbra-Community/account-history#24]
The installer will include audit.log and sync.log in /opt/zimbra/lib/ext/accountHistory/config.properties file . For speed, you can remove sync.log and the sync.log.yyyy-MM-dd.gz  for better speed.

In my environment of around 1000 users, it takes about 120 sec to find all logs with sync.log and below 10 sec without sync.log.

**Comment by ghost** [comment]
users with zextras suite need the sync.log to see log-ins via ActiveSync.

I will see if it still needed.

**Comment by naisiew** [comment]
Oh didn’t realize that. My setup has Mobile NG in my 8.8.15 NE, which supposed to be same as Zextras mobile. I don’t see string “account=“ in sync.log. Is there special search string in sync.log?

**Comment by ghost** [comment]
no it used to be the same.

Does the log rotation work?

**Comment by naisiew** [comment]
You mean does it read audit.log.yyyy-mm-dd.gz? Yes, as advertised. It reads today (audit.log) and yesterday's (audit.log.2020-03-23.gz) only.

**Comment by ghost** [comment]
I looked into it and ZSuite does now log correctly to audit.log. Which means we no longer need to parse sync.log. 

The only thing sync.log provides on top of audit.log is an indication of the device type. Aka android or iphone. But IMHO that is little information for the performance hit.

I have released a new version that patches the installer/UI and readme.
