### ISSUE TITLE
GoIP

### ISSUE THREAD

**Issue by xaviermedina** [Zimbra-Community/account-history#25]
Hola, instale el zimlet, me aparecen los datos bien, pero no me aparece el mapa de gmaps para ver la ubicacion de las ip de manera grafica en el mapa. que puede ser?

**Comment by ghost** [comment]
Do you only see internal or blank IP's? check:
 https://github.com/Zimbra-Community/account-history#log-external-ip

GeoIP2 database is not updated periodically, while the installer updated it just now, you can update it in the future by running:
 /usr/local/sbin/geoip2-zimbra-update.sh

The GeoIP database has A LOT of rate limiting nowadays, so maybe yours was not initialized.
