### ISSUE TITLE
History not regular update in zimbra 9

### ISSUE THREAD

**Issue by WibyHere** [Zimbra-Community/account-history#27]
Hi, I tried to install on zimbra 9 and during installation there were no problems, but the history provided did not appear immediately like there was a schedule (ex. I logged in at 9 am the history did not appear and when I query again at 10 the history appeared). is there really such a schedule? then sometimes when the query appears no data receive from the server even though 1 hour before I had logged in. I installed this in a multiserver environment and every mailbox has this application installed.

**Comment by ghost** [comment]
This extension reads log files, so you should check and see if there is indeed something logged and when.
