### ISSUE TITLE
i cant find the zimlet in administration page

### ISSUE THREAD

**Issue by floydu** [Zimbra-Community/account-history#5]
Zimbra Account History installed successful.
You still need to restart some services to load the changes:
su - zimbra -c "zmmailboxdctl restart"

But now i cant find it in the zimlets administration page.

**Comment by ghost** [comment]
Its under tools and migration

**Comment by floydu** [comment]
Ok i got it. And the map? where is?
>Update I find it

**Comment by floydu** [comment]
![image](https://cloud.githubusercontent.com/assets/27734020/25200162/fed1d7b4-2512-11e7-8222-78de7143f0cd.png)
There is no IP log When i use webmail

**Comment by ghost** [comment]
you need to configure zimbra as in the readme:
https://github.com/Zimbra-Community/account-history#log-external-ip
