### ISSUE TITLE
Zimlet disable Zimlet Board with New UI

### ISSUE THREAD

**Issue by Dual-Boot** [Zimbra-Community/account-history#6]
Hello,

 when enabling the Zimlet into ZCS FLOSS 8.7.7 and with Universal UI 0.7, the Zimlet Board in the main webmail window is disable and no other Zimlets are available.
 For information, I have the same behavior with Email Template Zimlet.

  Regards,

**Comment by ghost** [comment]
Maybe you could file this bug at the Universal UI team (jorge), as especially the Email Templates Zimlet, does nothing special. So in this case it seems an Universal UI bug.

Also, maybe dev is on a newer version of Zimbra 8.7.9?

I will ask and see when the Universal UI becomes ready to develop against, right now it seems to be in flux.
