### ISSUE TITLE
Which version?

### ISSUE THREAD

**Issue by timur-g** [Zimbra-Community/account-history#9]
I installed this today in 8.7.1 on Centos via commands you provided on https://zimbra.org/extend/items/view/zimbra-account-history 
In Configure - Admin Extensions it shows version 0.0.1 while web page shows 0.0.2. Why?

Immediately after installation, I see "No data received from server". No idea if this needs some restart.

**Comment by ghost** [comment]
The version number reflects the version of the Client Zimlet, that is 0.0.2. Then Admin Zimlet is at 0.0.1.

The installer always fetches the latest version, so no problems there.

No data received from server, means there is no information found in the log file, perhaps it has just rotated? See again, and see if there is something there now.
